### ISSUE TITLE
Emby 服务支持

### ISSUE THREAD

**Issue by 908468180** [dragonflylee/switchfin#1]

**Comment by dragonflylee** [comment]
@908468180 暂时还不支持 emby 的服务器，以后会考虑兼容 （非转码部分）

**Comment by 908468180** [comment]
大佬加油，感谢大佬的付出

**Comment by dragonflylee** [comment]
@908468180  可以试试这个 添加了对 emby 初步的支持

https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/emby

**Comment by dragonflylee** [comment]
由于 jellyfin 10.10 接口变化较大，以后就不做兼容了
