### ISSUE TITLE
无法播放高码率HEVC视频

### ISSUE THREAD

**Issue by zjmsjla** [dragonflylee/switchfin#2]
请问这个软件如何使用？
我成功安装打开并登录了我的jellyfin服务器，能看到媒体库，但是无法播放。在播放界面进度条为0，无具体时间显示，播放按钮无反应。
另外，希望该软件能自动创建桌面图标，类似wiliwili。
希望该软件能支持到1080P 40Mbps，而不只是现在的1080P 10Mbps。

**Comment by dragonflylee** [comment]
@zjmsjla  

1. 又由于技术限制，自制程序尚不能访问 GPU 音视频解码器 (参考 [Video HW Decoder #580](https://github.com/switchbrew/libnx/issues/580))，所有视频都是CPU软解的，因此对于Switch羸弱的CPU性能来说，软件10Mbps的H264视频就已经很吃力
2. 方便的话能否使用 Chrome 浏览测试一下 Web 版客户端是否正常播放，并提供类似下图播放信息截图
![image](https://github.com/dragonflylee/switchfin/assets/6219280/61e3eb9c-3acb-4f92-afa7-cddb3d377848)
3. 推测您的视频源可能为高码率(比如蓝光原盘)，方便的话能提供一下测试用的视频源（磁链网盘皆可）以供测试

> 实测像这种2M的HEVC都播放很吃力，包括不仅限于 音频不同步，掉帧卡顿

**Comment by zjmsjla** [comment]
1、在switch上的错误步骤入下
我的机子是国行破解版，这是在大气层虚拟系统中的情况。
可以看到能登录浏览海报，但是无法观看视频。进度条为0，播放按钮没反应，最后系统崩溃。
![IMG_20230720_195049](https://github.com/dragonflylee/switchfin/assets/119132323/d732e1c8-a410-458a-a938-029b9dfa3039)
![IMG_20230720_195100](https://github.com/dragonflylee/switchfin/assets/119132323/e02b022b-f50e-461a-b5d2-92a2ac94791b)
![IMG_20230720_195113](https://github.com/dragonflylee/switchfin/assets/119132323/18bf9404-75ef-4b94-a5d2-5a21ef87b2ae)
![IMG_20230720_195210](https://github.com/dragonflylee/switchfin/assets/119132323/27550e32-9f9d-48a9-ad42-0c5b98816b2a)

2、这是使用谷歌浏览器的播放界面，同时我的Windows客户端、安卓客户端都可以正常观看。
![IMG_20230720_195817](https://github.com/dragonflylee/switchfin/assets/119132323/5411b812-8ca9-42da-baab-91062a4d1162)

3、附件中是视频源文件，由于视频过大无法上传，所以是种子文件
链接：https://pan.baidu.com/s/1dy7BJhGiEdNwc4y9_65cRw?pwd=6eys 
提取码：6eys
十分感谢。

**Comment by dragonflylee** [comment]
@zjmsjla  感谢测试反馈

HEVC 26Mbps的原片基本不可能在 HOS 系统下播放，建议开启Jellyfin服务端转码，或者使用H264的片源。转码触发参数近期正在调整中

**Comment by zjmsjla** [comment]
可以播放了，但是只能小概率播放。当加载视频时，有可能卡死崩溃，崩溃代码2168-0001.
另外，我发现小程序+系统内存无法超过620M，这是switch系统限定的吗，有没有可能进一步扩展小程序的运行内存。

**Comment by dragonflylee** [comment]
@zjmsjla 你是不是在相册中启动的呀 随便找个游戏按R键启动hbmenu

**Comment by dragonflylee** [comment]
@zjmsjla 

~这里先做了一个 NSP 桌面图标，稍后会集成到应用里~
~[Switchfin-forwarder.zip](https://github.com/dragonflylee/switchfin/files/12139137/Switchfin-forwarder.zip)~

NSP forwarder 已集成

**Comment by zjmsjla** [comment]
以上问题基本解决了，但是又有新问题。

1、码率
码率默认为”自动“,这个模式下不知道是什么情况，我怀疑是原码播放，播放超过10M码率的4K会卡顿，播放高码率4K视频时手动选择”1080P 10M“码率则没有问题。”自动“码率播放1080P 14M视频没有问题。
不过这一点可能是你之前提到的”转码触发参数“的问题，等你调试好应该就没事了。
播放14M码率1080P视频，CPU不超频，实测手动选”1080P 10M“码率，CPU占用三核不超过61%，”自动“码率下CPU占用不超过97%，均能流畅播放。如果CPU超频到1750MHz，”自动“码率下CPU占用不超过70%。所以希望能加入”1080P 15M“码率的选项，CPU还能顶得住。
同时这个并不能记忆上一次选择的码率，这次选了1080P 10M，下次进去还是”自动“。

2、按钮
使用手柄选择码率非常困难，选择框一直在”播放“、”设置“、”TV“三个图标中徘徊。目前只有触屏选择码率后才有可能通过手柄选择码率，但仅限这一次播放，并且隐藏控制栏后再呼起无法再次手柄选择码率。
播放/暂停按钮并不能时常奏效，很难触发暂停。

3、崩溃
在播放过程中，按到”X“必然崩溃，按”B“退出播放必然崩溃，打开“齿轮”图标概率崩溃。
这些是通过HBMEMU打开switchfin的崩溃情况，通过相册打开时”B“和”齿轮“的崩溃概率相反，还有可能触屏崩溃，不过这个可以不管。

4、图标
今天凌晨发的图标并不能正常使用。不论是直接在桌面打开，还是通过该图标进入HBMEMU再打开switchfin，能看到海报，但都不可交互，不论触屏还是手柄。
这个可以等你整合之后我再试试。

我的服务端是10.8.9版本，镜像nyanmisaka/jellyfin:230414-amd64。

**Comment by dragonflylee** [comment]
@zjmsjla  问题 2，3，4 大概率都解决了，请到 actions 下载最新编译的版本 https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev

关于解码方面似乎有人在研究 HOS 下的硬解支持，到时候应该会好很多

**Comment by zjmsjla** [comment]
因为这半个月在外面，所以网速受限，只有4Mbps，只能简单测试一下。
目前软件内基本没有问题了，能正常播放，没有崩溃，按键好用，超频还没有测试条件。等我回家了再详细测试一下。
GPU解码实在不支持问题也不大了，10M码率应对switch输出的1080P60FPS刚刚好，只要能解决自动码率不触发转码的问题就很实用了。

目前发现两个小毛病，不过也不一定是该程序的问题。
选择字幕后不能及时加载，不过我在web端播放也遇到过，而且这个我还没有仔细测试。
通过生成的桌面图标进入，依然无法交互。我不清楚是当初安装的图标的问题（因为之前图标进入也无法交互），即使我是先卸载图标再生成的，还是0.1.1版本自身就有问题。你可以等等别人的反馈。

**Comment by zjmsjla** [comment]
又小试了以下，有四个问题。
1、播放视频，退出后会丢失选择蓝框。
2、无法显示选择视频自带字幕，选择外挂字幕无效果。
3、部分视频无声音，在别的客户端有声音。
4、通过生成的桌面图标进入程序，无法交互。

另外还有一个，不知道算不算，退出该服务器后，无法记录服务器账密。

**Comment by dragonflylee** [comment]
@zjmsjla  感谢您的测试，
1.NSP前端问题我这边确实无法复现。建议您使用最新的 [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/releases//latest) 和系统固件 [NX_Firmware](https://github.com/THZoria/NX_Firmware/releases/latest)
2.如果遇到XXX没声音或者无法播放的问题，建议用 [mediainfo](https://mediaarea.net/en/MediaInfo) 查一下媒体格式，否则开发者没有具体信息也无从下手。
3.字幕问题有可能是字幕文件编码问题，也可能是字体缺失。建议将字体文件（比如 SimHei.tff）放到 `/switch/Switchfin/subfont.ttf`
4.服务器管理目前还没开发完，只有简单登录的功能

**Comment by dragonflylee** [comment]
@zjmsjla 硬解支持已添加，可以播放4K视频啦，但是杜比视界的视频似乎颜色不太对
![2023091120272500-5B7216B739EC78EC87BE86111C78E4A1](https://github.com/dragonflylee/switchfin/assets/6219280/d1a4030e-6689-4943-98a2-58a56c38fbac)

**Comment by zjmsjla** [comment]
色彩失衡是因为jellyfin本身不支持杜比视界，要开启色调映射。官方镜像不确定是否支持，不过nyanmisaka的特供版镜像可以。我是先装了特供版镜像然后升级到官方镜像的。
![IMG_20230911_204307](https://github.com/dragonflylee/switchfin/assets/119132323/30ccfac9-0f66-472a-acd8-eec792f13f6c)

目前基本完善了，一些无伤大雅的小问题也无所谓。对我个人而言，主要有两个使用问题。
1、桌面图标不可交互。
我是国行机器，升级了16.10.0系统和1.5.5大气层，内存卡改了fat32，重装的wiliwili的桌面图标可用，但是switchfin的图标一直无法交互。如果你一直是正常的，就不用管这条了。找到有些说法是证书丢失，等我懒癌好了再看看吧。
2、字幕无法显示
我记得在0.1.0版本是会自动显示的还是怎样，忘记了。我在switch指定文件夹里，放一个、放几个.tff文件都试过了，服务端启用不启用备用字体也试过了，不行，用的是小米的misans和方正的仿宋、宋体、黑体、楷体，没试过改名伪装jellyfin的dajevu。

然后是一点功能上的问题。
1、会增加对音乐的支持吗？因为jellyfin也能当个音乐服务器，而且switch好像还没有本地在线音乐播放器。
2、新版本支持了ipv6，但是switch好像本身不支持ipv6吧，在设置里也看不到分配的ipv6地址，没找到具体资料，不确定。但是影响不大，openwrt的nat回流还搞不定，我的ipv4也是内网ip。

**Comment by dragonflylee** [comment]
音乐播放器有一个 [TriPlayer](https://github.com/tallbl0nde/TriPlayer)  ，因为原版太久没维护了我自己fork编译了一份 https://github.com/dragonflylee/TriPlayer/releases/download/v1.1.2/triplayer.zip ，能自动从 musicbrainz 抓取信息，很赞

对 jellyfin 的音乐支持目前还在开发中 https://github.com/dragonflylee/switchfin/tree/feats/music

**Comment by zjmsjla** [comment]
乌龙了，我的马里奥我换源了，没有杜比视界。然后我换了个杜比视界视频也是色调失衡，各个客户端转码直播都是色调失衡，看来要换回nyanmisaka的镜像。
十分感谢你的音乐播放器。

**Comment by dragonflylee** [comment]
@zjmsjla 有时间的话能帮忙测一下这个版本 的桌面图标能正常使用吗?

[Switchfin.nro.zip](https://github.com/dragonflylee/switchfin/files/12586868/Switchfin.zip)

**Comment by zjmsjla** [comment]
1、桌面图标依然不可以使用。然后我又看了下，和签名补丁好像没关系。
2、要解决字幕的问题，除了把.tff字体文件放在/switch/switchfin里面，还有更细致的要求吗？文件名称、字体、文件数量这些的。
3、今天换了镜像，直播还是偏色，转码可以正常显色。
![IMG_20230913_000757](https://github.com/dragonflylee/switchfin/assets/119132323/68c7db9b-9f92-40a2-af59-4625843b31ed)
![IMG_20230913_000737](https://github.com/dragonflylee/switchfin/assets/119132323/46b5deeb-795f-4c39-9450-3c0299d4a9ae)

**Comment by dragonflylee** [comment]
@zjmsjla  字体文件固定文件名 `/switch/Switchfin/subfont.ttf`，我用的是 `方正准圆_GBK `

**Comment by zjmsjla** [comment]
1、字幕正常了，是我太笨，我还以为之前那个subfont是“字幕字体”的代指，随便放个.tff就行。
2、桌面图标，是和wiliwili实现方式不同的原因吗，还是别的。我在switchfin文件家里看到有个.star文件，这和图标有关系吗?然后我不管是把switchfin.nro放在/switch还是放在/switch/switchfin，都会读取switch/switchfin/config.json，都会在switchfin.nro相同文件夹生成.star文件，很怪。

**Comment by dragonflylee** [comment]
.star 文件应该是 hbmenu 标记收藏的，与桌面图标无关

**Comment by xfangfang** [comment]
@zjmsjla wiliwili 现在用的桌面图标也是 @dragonflylee 帮忙写的编译脚本，所以不应该出什么问题的。

桌面图标会优先打开：`sdmc:/switch/Switchfin.nro` ，如果不存在则打开 `sdmc:/switch/Switchfin/Switchfin.nro`

所以在测试时，最好把应用直接放在 switch 目录下，避免开启了错误的 nro

**Comment by dragonflylee** [comment]
目前硬解支持良好，如果 NSP Forwarder 还有问题可以单独提 issue
