### ISSUE TITLE
Crash when signing in to new user on 0.3.0

### ISSUE THREAD

**Issue by grimpy** [dragonflylee/switchfin#25]
When using the app with an existing user it works fine, but when i try to login with another user it always force closes

**Comment by dragonflylee** [comment]
which platform you use? win or osx or ns!

you can try to remove `config.json` from
config dir

**Comment by grimpy** [comment]
That worked! Thanks I do want to note when I entered a wrong password it
still force closed but with the correct credentials it loged in and worked

**Comment by dragonflylee** [comment]
@grimpy try https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev which fixed crash

**Comment by grimpy** [comment]
Thanks I'll try to check it out later today

**Comment by grimpy** [comment]
This works in 0.3.1 I'll close
