### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by PhamMinhKha** [dragonflylee/switchfin#26]
### Is your feature request related to a problem? Please describe.

I was very surprised when the switch installed SwitchFin. It works very well. Thank you for making it. It would be better if it supported Vietnamese subtitles.

**Comment by dragonflylee** [comment]
to resolve subtitles display, please put font file to `/switch/Swichfin/subfont.ttf`

for ui translate, welcome to contribute i18n file https://github.com/dragonflylee/switchfin/tree/dev/resources/i18n

**Comment by PhamMinhKha** [comment]
Thank you. I did it. Vietnamese displays very well. You are wonderful
