### ISSUE TITLE
Add Support for Jellyfin Live TV channels / tunners

### ISSUE THREAD

**Issue by Elratauru** [dragonflylee/switchfin#27]
### Is your feature request related to a problem? Please describe.

I'd like to be able to watch the Live TV channels you can setup on Jellyfin.

Right now, if you set up an Live TV Tunner to Jellyfin you cannot see any channels being listed through the interface, even though you see it's icon on Switchfin, it acts as an empty folder.

### Describe the solution you'd like

A solution would be to list the channels and play them inside this Live TV shortcut on the home interface. Jellyfin does has more features regarding LiveTV (Program guides come to mind) but having the option to list the different channels as well as playing them would fulfil the main requirement of the feature.

As an example, Here is a public list of channels that can be used to reproduce the current behaviour: 
https://iptv-org.github.io/iptv/countries/jp.m3u

To setup the LiveTV options on the Jellyfin server you can check this guide:
https://jellyfin.org/docs/general/server/live-tv/setup-guide

### Describe alternatives you've considered

Currently there's no other software that lets you open a m3u stream directly.

**Comment by dragonflylee** [comment]
not plan for this

**Comment by dragonflylee** [comment]
@Elratauru initial support of live tv support was added in latest  [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)
