### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by waveblitzd** [dragonflylee/switchfin#29]
### Describe the bug

On latest release, switch firmware 17.0, local jellyfin server (not proxy)

Menus, search etc all load fine, but none of the media seems to be playing. It just hangs on a black screen no matter the size of the video.

### Operating system

17.0.0|AMS 1.6.2|S

**Comment by dragonflylee** [comment]
please use [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) and turn on debug view in setting tab, then take screenshop when play video

**Comment by waveblitzd** [comment]
![image](https://github.com/dragonflylee/switchfin/assets/83782418/4bd6b466-07fb-4871-a500-69b8ac4c4917)

**Comment by dragonflylee** [comment]
it shows something wrong with video stream, can you show detail about video media info

another way try to turn on `Force direct play`

**Comment by waveblitzd** [comment]
![image](https://github.com/dragonflylee/switchfin/assets/83782418/369f862d-f936-47de-b52e-336fd8fcbac4)

I have tried to force direct play and the issue persists.

**Comment by dragonflylee** [comment]
make sure your jellyfin server is 10.8.9 or newer

**Comment by waveblitzd** [comment]
server is 10.8.11

**Comment by dragonflylee** [comment]
@waveblitzd  try https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev/switchfin-switch-043927d.zip which add more log to debug view

**Comment by waveblitzd** [comment]
![image](https://github.com/dragonflylee/switchfin/assets/83782418/a5fa26b6-593a-453d-8b3d-55868f5ff87b)

**Comment by dragonflylee** [comment]
your server address missing scheme `http://`,  should be `http://10.0.0.105:9000`

**Comment by waveblitzd** [comment]
fixed the problem, ty!
