### ISSUE TITLE
Can't navigate playback interface with dpad/analog stick unless screen is touched first.

### ISSUE THREAD

**Issue by kevsestrella** [dragonflylee/switchfin#30]
### Describe the bug

Switchfin 0.3.3
Can't navigate playback interface with dpad/analog stick unless screen is touched first. Both on dock and handheld.

### To reproduce

2. Tap on '....'

### Operating system

17.0.0|AMS 1.6.2|E

**Comment by dragonflylee** [comment]
fixed in latest [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)
