### ISSUE TITLE
Realistic Speed control on playback + buttons for speed activation

### ISSUE THREAD

**Issue by vegedb** [dragonflylee/switchfin#31]
### 1. Realistic Usable speed control
It's not practical or realistic to have anything more than 2.5x for videos.
Also, its setting is not gradual.
Please adjust it to 1x, 1.5x, 2x, 2.5x. Maybe 1.25 or 1.75 if you want to!

### 2. Add button support for speed
This is another great thing to have as well!

**Comment by dragonflylee** [comment]
add LSB Button for trigger speed selection , you can test by [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)
