### ISSUE TITLE
Face buttons(A button) doesn't work for selecting server from Server List in Login Screen

### ISSUE THREAD

**Issue by kevsestrella** [dragonflylee/switchfin#33]
### Describe the bug

Server from the list has to be tapped to be selected. When the switch is docked, it has to be undocked first.

Switchfin 0.3.3 - 0.4.0

### To reproduce

2. Tap on '....'

### Operating system

17.0.0|AMS 1.6.2|E

**Comment by dragonflylee** [comment]
Thanks for feedback, this issue was resolved by https://github.com/dragonflylee/switchfin/commit/dc6e76f7a3e594e1f29cbb0e7f42a1aae90936d9

You can test by [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

**Comment by kevsestrella** [comment]
Thanks for actively developing the app. Tested, it works. Closing now.
