### ISSUE TITLE
'http status 400' error when logging in

### ISSUE THREAD

**Issue by TygaMike** [dragonflylee/switchfin#34]
### Describe the bug

I can connect to my Jellyfin server, but when I try to log in with my credentials or quickconnect I get a 'http status 400' message and cannot access the files on my server.

### To reproduce

1. Open app
2. Add server
3. Click sign in button
4. Enter credentials or select quickconnect
5. See error

### Operating system

16.0.3|AMS 1.5.5|E

### Jellyfin Server

10.8.12 Windows

**Comment by dragonflylee** [comment]
maybe something wrong with `deviceid`, try [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

if not work, try delete `/switch/Switchfin/config.json` on sd card

**Comment by TygaMike** [comment]
Still the same issue. Just to be sure, the nightly version is 0.4.0, right? Otherwise, maybe the issue is that I'm using http rather than https? I assume the IP I use to connect would be the same one I use with my phone, right?

**Comment by dragonflylee** [comment]
after libnx update to v4.5.0, [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere) should upgrade ot 1.6.0 or above

**Comment by TygaMike** [comment]
Updated everything and having the same issue. Though the most recent firmware prevents my console from going online without Atmosphere crashing anyways, so I guess it's a moot point.

**Comment by AndreaDiNapoli** [comment]
I get the same error, I can't login no matter what I try.
Atmosphere is updated and I tried removing the config file.

**Comment by dragonflylee** [comment]
@AndreaDiNapoli  try fill `/switch/Switchfin/config.json` with following content before startup

```json
{
  "device": "MySwitch01"
}
```

**Comment by TygaMike** [comment]
> @AndreaDiNapoli try fill `/switch/Switchfin/config.json` with following content before startup
> 
> ```json
> {
>   "device": "MySwitch01"
> }
> ```
I got my internet stuff fixed and then tried this and it worked. Thanks.

**Comment by AndreaDiNapoli** [comment]
> > @AndreaDiNapoli try fill `/switch/Switchfin/config.json` with following content before startup
> > ```json
> > {
> >   "device": "MySwitch01"
> > }
> > ```
> 
> I got my internet stuff fixed and then tried this and it worked. Thanks.

It worked perfectly! Thank you!
