### ISSUE TITLE
Login Disclaimer Display

### ISSUE THREAD

**Issue by kevsestrella** [dragonflylee/switchfin#36]
### Is your feature request related to a problem? Please describe.

No, it's not much of a problem, I was just thinking it would be great to have users see a message this way

### Describe the solution you'd like

Display the Login Disclaimer of the server, maybe under the server version / OS at the Login Page

![Screenshot_20231123-233558_Trebuchet](https://github.com/dragonflylee/switchfin/assets/24399573/da796257-913a-48b2-8deb-52eb2ef0f2d5)

![IMG_20231123_234432](https://github.com/dragonflylee/switchfin/assets/24399573/2ac544ea-c2c8-4d97-80b2-0e58cc3bc46c)

**Comment by dragonflylee** [comment]
Thanks for suggest, this feature was added by https://github.com/dragonflylee/switchfin/commit/a991e4b65d194c4d6c62442653ae9d2550658254

You can test by [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

**Comment by kevsestrella** [comment]
Thanks, It works, closing it now.

![IMG_20231124_064343](https://github.com/dragonflylee/switchfin/assets/24399573/17e258e0-6e47-4d33-a577-7972b4e2bfe7)
