### ISSUE TITLE
Add to E-Shop

### ISSUE THREAD

**Issue by TriVoxel** [dragonflylee/switchfin#38]
### Is your feature request related to a problem? Please describe.

Currently unavailable to install on retail Switch

### Describe the solution you'd like

Would love to simply install from E-Shop.

### Describe alternatives you've considered

It is likely to remain homebrew.

### Additional context

Made this issue simply to ask if an official release was planned. If so, this issue can be updated to track the progress of a first E-Shop release. My understanding is that this is a ways off, but I am excited for the prospect of being able to stream to my Switches!

**Comment by dragonflylee** [comment]
homebrew only be installed on custom firmware
