### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by skylegend509** [dragonflylee/switchfin#39]
I made a ukrainian translation for your app. However, i don't have console or emulator for test it on, so it might need some editing. 
I also added the line "ukrainian": "Українська" in main.json > language. 
You also don't have a detailed guied on how to createn a translation, so if there's something I'm missing or haven't done, let me know.
[uk-UA.zip](https://github.com/dragonflylee/switchfin/files/13997668/uk-UA.zip)

**Comment by dragonflylee** [comment]
sorry, [borealis](https://github.com/dragonflylee/borealis) which switchfin depends does not support ukrainian yet

**Comment by skylegend509** [comment]
That's sad, but thanks for the feedback!

**Comment by dragonflylee** [comment]
add Ukrainian translation to setting tab, but not auto detect by system
