### ISSUE TITLE
音乐显示界面

### ISSUE THREAD

**Issue by zjmsjla** [dragonflylee/switchfin#40]
### Is your feature request related to a problem? Please describe.

因为我的音乐文件全部是单曲放一起的，而目前switchfin默认界面是专辑，导致使用switchfin无法显示歌曲。单曲存放，在web端可以显示歌曲但是不能显示专辑。
因为我主要从网易云和QQ音乐获取音乐文件，网易云还好，可以按照作者/专辑/歌曲的顺序直接下载存放，但是QQ音乐就不太行，所以只能按照两者通用的单曲存放。

### Describe the solution you'd like

如果可以的话，希望增加自选歌曲的首选界面的功能，就和jellyfin客户端一样。

### Describe alternatives you've considered

或者可以推荐一下一些自动化的刮削分类工具吗，又或者是更契合jellyfin的音乐源获取方式？

**Comment by dragonflylee** [comment]
可以的话能描述一下您那边的音乐文件的目录结构吗？比如这样

```
Game
├── 2002 - AIR ORIGINAL SOUNDTRACK
│   ├── Disc 1
│   │   ├── 01. 回想録.flac
│   │   ├── 02. 野道.flac
│   │   ├── 03. 鳥の詩.flac
│   │   └── cover.jpg
│   ├── Disc 2
│   │   ├── 01. 鳥の詩 ~short version~.flac
│   │   ├── 02. Farewell song ~short version~.flac
│   │   └── cover.jpg
│   └── Folder.png
├── 2018 - Xenoblade2 Original Soundtrack
│   ├── Disc 1
│   │   ├── 01. Xenoblade II - Where It All Began -.flac
│   │   ├── 02. Elysium, in the Blue Sky.flac
├── Disc 2
│   │   ├── 01. 巨神獣戦艦.flac
│   │   ├── 02. Monster Surprised You.flac
│   └── Folder.jpg
```

> PS: 我这边目前都是手工整理的

**Comment by zjmsjla** [comment]
好像解决了，这俩软件都支持歌手/歌曲的存放方式，就是jellyfin推荐的这种
/Music
    /Artist
        01 - Song.flac
        02 - Song.flac
按照这种方式可以正常刮削并显示
