### ISSUE TITLE
Steamdeck support

### ISSUE THREAD

**Issue by mlyxshi** [dragonflylee/switchfin#42]
### Describe the solution you'd like

flatpak support
https://github.com/xfangfang/wiliwili/discussions/41

**Comment by dragonflylee** [comment]
you can test with https://nightly.link/dragonflylee/switchfin/actions/runs/8138454464/Switchfin-flatpak-132e2de-x86_64.zip

by `sudo flatpak install Switchfin-flatpak-132e2de-x86_64.flatpak`

**Comment by mlyxshi** [comment]
flatpak 上配置无法持久化，登录页面位置有些错位
播放功能正常

**Comment by dragonflylee** [comment]
https://nightly.link/dragonflylee/switchfin/actions/runs/8431456266/Switchfin-flatpak-4638e7e-x86_64.zip

这个版本修复了配置文件问题
