### ISSUE TITLE
error 101

### ISSUE THREAD

**Issue by ender2007225** [dragonflylee/switchfin#43]
### Describe the bug

URL=http://192.168.50.232:28096
jellyfin 10.8.13
[json.exception.parse_error.101]parse error at line 1,column 1:syntax error while parsing value - invalid literal;last read:'<'

![image](https://github.com/dragonflylee/switchfin/assets/109329067/6c55dfbe-df47-4ba9-91e9-21f32c16621d)

### To reproduce

2. Tap on '....'

**Comment by dragonflylee** [comment]
1.`Base Url` in jellyfin server setting should not be started with `/`
2.When, Where and How to reproduce de error message you see ?
3.Which platform you use, and which version of atmosphere you use ?

**Comment by ender2007225** [comment]
Thank you. The issue was resolved after removing the Base URL. It seems that the problem occurred because I didn't restart the Jellyfin server after deleting it. I don't remember the exact purpose of this Jellyfin setting, but its presence doesn't affect other Jellyfin clients or the web interface. The versions used are Atmosphere 1.6.2, 17.0.1, and Switchfin 0.4.4.
