### ISSUE TITLE
Stuck on loading library contents

### ISSUE THREAD

**Issue by kevsestrella** [dragonflylee/switchfin#44]
### Describe the bug

Occurs while browsing libraries, it gets stuck on loading media until refresh(x) is pressed. On debug view, ```error.performSyncTasks: [json.exception.type_error.302] type must be string, but is null``` is shown. This happens to 0.4.4 but not on 0.4.3

### To reproduce

2. Tap on '....'

### Screenshots

![2024032618025500-5B7216B739EC78EC87BE86111C78E4A1](https://github.com/dragonflylee/switchfin/assets/24399573/a7a13522-8cf7-4480-9dd6-99aa84e20e65)

### Operating system

17.0.1|AMS 1.6.2|E

### Jellyfin Server

10.8.13

### Additional context

happens on 0.4.4/latest nightly but not on 0.4.3

**Comment by dragonflylee** [comment]
Sorry for coming late, try this test build https://nightly.link/dragonflylee/switchfin/actions/runs/8518445236 may solve this issue

**Comment by dragonflylee** [comment]
@kevsestrella  Fixed in https://github.com/dragonflylee/switchfin/commit/d54afe5e358ceac94b1638123f8bb8c7746781f6
you can donwload test build from https://nightly.link/dragonflylee/switchfin/actions/runs/8588692848

**Comment by Endyxd** [comment]
I am having this same issue with my switch, I am able to connect on other devices I am just unable to connect with SF 0.4.4. I even tried regressing to 0.4.3 and it didn't work either. Thank you for your time.

**Comment by dragonflylee** [comment]
@Endyxd is latest build  [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) has same issue?

**Comment by abysphalt** [comment]
Latest nightly has fixed the issue

**Comment by kevsestrella** [comment]
Hi @dragonflylee , thanks for looking into this. @abysphalt is right, the issue doesn't occur on the latest nightly.

**Comment by Endyxd** [comment]
> @Endyxd is latest build [![nightly](https://camo.githubusercontent.com/5ab7f1a946865ae5191baea212a789a5c542f67d85d8a34af0aaf42ca3bda318/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) has same issue?

I actually got it working, I think it had to do with file permissions, I don't think the library liked being on my desktop. I have no idea it worked on my phone before, but moving the folder seemed to have it working on switchfin now.
