### ISSUE TITLE
Subtitles not displaying on some episodes

### ISSUE THREAD

**Issue by nouun** [dragonflylee/switchfin#45]
### Describe the bug

Subtitles are enabled and work on the web client but do not work on Swiftfin. 

### To reproduce

1. Play episode
2. Select subtitles
3. Play
4. No subtitles show up

### Screenshots

![IMG_2962](https://github.com/dragonflylee/switchfin/assets/92670069/88801f49-5a55-4932-8426-a4ebef9433b9)
![IMG_2964](https://github.com/dragonflylee/switchfin/assets/92670069/ba5d32a3-0f99-425e-a52e-e8a52645cfc1)
![image](https://github.com/dragonflylee/switchfin/assets/92670069/123ef5be-651e-4567-aac5-cf23d808758a)

### Operating system

17.0.1|AMS 1.6.2|E

### Jellyfin Server

10.8.13 Linux

**Comment by dragonflylee** [comment]
try put any `ttf` font file at `/switch/Switchfin/subfont.ttf`

**Comment by nouun** [comment]
> try put any `ttf` font file at `/switch/Switchfin/subfont.ttf`

I can't find which font is missing, it doesn't say anywhere and if I extract the subtitles they don't seem to specify a font.

**Comment by dragonflylee** [comment]
you can copy `ttf` file from pc, such as `arial.ttf`

**Comment by nouun** [comment]
My apologies, I missed the "any" part. That fixed it, thank you very much!

Would it be possible to add that to the README somewhere for future users or add a pop up if they try play a video while that font is missing?

**Comment by dragonflylee** [comment]
thanks for suggestion, I will add subfont notice in next release

**Comment by nouun** [comment]
Thanks again! Closing as solved.
