### ISSUE TITLE
music video didn't work

### ISSUE THREAD

**Issue by Xmoncoco** [dragonflylee/switchfin#50]
### Describe the bug

I see the different ui of my music videos but I can't access them.

### To reproduce

just go to an music video and try to launch nothing append 

### Operating system

17.0.0|AMS 1.7.0|E

### Jellyfin Server

10.8.13 Linux

### Additional context

like I say earlier I weird that the music video folder of my jellyfin have a different layout than my Tv series

**Comment by dragonflylee** [comment]
Fixed by https://github.com/dragonflylee/switchfin/commit/4c001f36f178a213b2ce392cee360687dc66d02d 
you can test with latest [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

Thanks for feedback
