### ISSUE TITLE
Emby支持

### ISSUE THREAD

**Issue by YiHooong** [dragonflylee/switchfin#51]
### Is your feature request related to a problem? Please describe.

大佬好 想知道Emby和jellyfin师出同源 能否做一下支持呢？我在最新的版本上试了可以连接到Emby服务器，图片缩略图和列表部分正常，但是播放提示 timeout was reached 希望可以看看
![IMG_20240510_144407](https://github.com/dragonflylee/switchfin/assets/120007008/8f0383ec-b076-40b4-aeb8-941fc8e511ff)

**Comment by dragonflylee** [comment]
与这个 https://github.com/dragonflylee/switchfin/issues/1 重复了

https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/emby

目前这个分支添加了对 emby 初步的支持，还需要一些重构才能将两者合二为一
