### ISSUE TITLE
通过桌面图标打开会卡死没反应

### ISSUE THREAD

**Issue by Mpinkings** [dragonflylee/switchfin#52]
### Describe the bug

通过桌面图标打开会卡死没反应

### To reproduce

2. Tap on '....'

**Comment by dragonflylee** [comment]
@Mpinkings  能否提供一下系统版本，大气层版本， 是不是国行机器？

**Comment by Mpinkings** [comment]
系统版本：18.0.0
AMS版本：1.7.0
国行机器



***@***.***
 
发件人： dragonflylee
发送时间： 2024-05-21 17:38
收件人： dragonflylee/switchfin
抄送： Mpinkings; Mention
主题： Re: [dragonflylee/switchfin] 通过桌面图标打开会卡死没反应 (Issue #52)
@Mpinkings 能否提供一下系统版本，大气层版本， 是不是国行机器？

**Comment by dragonflylee** [comment]
该问题似乎只有在国行机器上出现过，但是我这边并没有类似问题出现

**Comment by dragonflylee** [comment]
@Mpinkings 可以尝试删掉桌面后，再使用这个 https://nightly.link/dragonflylee/switchfin/actions/runs/9184441636/Switchfin-deko3d-e3d0bbe.zip 看看还会不会卡死

**Comment by Mpinkings** [comment]
可以了，非常感谢，另外提一个小建议，B键退出播放能否增加一个退出确认功能，有时候会误操作



***@***.***
 
发件人： dragonflylee
发送时间： 2024-05-22 11:47
收件人： dragonflylee/switchfin
抄送： Mpinkings; Mention
主题： Re: [dragonflylee/switchfin] 通过桌面图标打开会卡死没反应 (Issue #52)
@Mpinkings 可以尝试删掉桌面后，再使用这个 https://nightly.link/dragonflylee/switchfin/actions/runs/9184441636/Switchfin-deko3d-e3d0bbe.zip 看看还会不会卡死

**Comment by dragonflylee** [comment]
@zjmsjla 问题解决可以关闭了
