### ISSUE TITLE
大佬 可以搞个PS4 版的吗 或者 ps4的kodi

### ISSUE THREAD

**Issue by TomYule** [dragonflylee/switchfin#53]
### Is your feature request related to a problem? Please describe.

大佬 可以搞个PS4 版的吗 或者 ps4的kodi

### Describe the solution you'd like

大佬 可以搞个PS4 版的吗 或者 ps4的kodi

### Describe alternatives you've considered

大佬 可以搞个PS4 版的吗 或者 ps4的kodi

### Additional context

大佬 可以搞个PS4 版的吗 或者 ps4的kodi

**Comment by dragonflylee** [comment]
编译了 PS4 版本， 暂时没有实机测试

https://nightly.link/dragonflylee/switchfin/actions/runs/9536505157/ps4-35829b2.zip

**Comment by dragonflylee** [comment]
@TomYule  最新编译的版本 Webdav 的支持 [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

相关配置如下

```json
{
  "remotes": [
    {
      "name": "xiaoya",
      "passwd": "guest_Api789",
      "url": "webdav://192.168.1.5:5678/dav",
      "user": "guest"
    }
  ]
}
```
