### ISSUE TITLE
貌似软件不能保存设置

### ISSUE THREAD

**Issue by ChrisShen-github** [dragonflylee/switchfin#54]
### Describe the bug

我用的windows端，想进去改个语言，退出重进以后还是英语
![QQ截图20240613202435](https://github.com/dragonflylee/switchfin/assets/37608623/4c2b8ac4-ec94-4939-8f1f-1281879cfad4)
![QQ截图20240613203306](https://github.com/dragonflylee/switchfin/assets/37608623/b421f0b1-c3d6-4f80-82d1-f46f4815c643)

并且好像所有的设置都不能保存，连上了jf服务器，下次打开软件又要重连了，有点麻烦，尝试了两个版本都是这样，可能是没有历史记录的功能？不过一些设置没法保存还是有点麻烦的，麻烦大佬看看

### To reproduce

2. Tap on '....'

### Operating system

windows

**Comment by dragonflylee** [comment]
Windows 下的配置文件存放在 `%localappdata%\Switchfin` 下面，是不是您的用户名含有中文或者其他特殊字符呢？建议看看 `%localappdata%` 下面有没有 `Switchfin` 这个文件夹

**Comment by ChrisShen-github** [comment]
C:\Users\用户名\AppData\Local  下面没有Switchfin文件夹，我的用户名是中文的，大概率是这个原因了，不知道您有什么解决办法？

**Comment by dragonflylee** [comment]
@ChrisShen-github  最新编译的版本已修复该问题

https://nightly.link/dragonflylee/switchfin/actions/runs/9502205809

**Comment by ChrisShen-github** [comment]
> @ChrisShen-github 最新编译的版本已修复该问题
> 
> https://nightly.link/dragonflylee/switchfin/actions/runs/9502205809

感谢大佬问题已解决！
