### ISSUE TITLE
Can we pull the config file from github?

### ISSUE THREAD

**Issue by laleeroy** [dragonflylee/switchfin#56]
### Is your feature request related to a problem? Please describe.

Im not a developer so I have no idea how hard it is to implement but I hope you can

Similar to tinfoil, is it possible if we pull the config files that has the url, login credentials from a rawgithub file?
I can't open my port on my internet provider, and I want to host outside of my network, If this is possible, I could just edit the config file online and push the changes to GitHub.
I used ngrok to tunnel but everytime I restart the service, the ip/link changes and I need to reedit the config file manually from the switch sdcard, it would be easy if the config will be pull from github file instead.
https://raw.githubusercontent.com/user/repo/config.json

**Comment by dragonflylee** [comment]
what about reading ip and port from dns record which called `IP4P`?

https://github.com/heiher/natmap
