### ISSUE TITLE
SSL peer certificate or SSH remote key was not okay

### ISSUE THREAD

**Issue by kevsestre** [dragonflylee/switchfin#58]
### Describe the bug

Issue occurs on newly setup switches with 0.5.0 switchfin. Doesn't occur on 0.4.5 or other clients

![received_340014465798164](https://github.com/dragonflylee/switchfin/assets/170945487/3fea51ca-8bb3-48c9-80a3-1fdcc80b9dfa)

### To reproduce

2. Tap on '....'

### Operating system

18.1.0|AMS 1.7|E

### Jellyfin Server

10.9.6 Linux

**Comment by dragonflylee** [comment]
turn off `tls verify` in network setting

**Comment by dragonflylee** [comment]
@kevsestre fixed by latest [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)
