### ISSUE TITLE
Problem to compile

### ISSUE THREAD

**Issue by hhgokraken** [dragonflylee/switchfin#59]
### Describe the bug

Documentation upgrade. Need to install 

`sudo dkp-pacman -S switch-libmpv`

Problem to build, faulty repository

```
CMake Error at scripts/forwarder/CMakeLists.txt:16 (message):
  Could not find hacbrewpack: try installing
  https://github.com/The-4n/hacBrewPack
```

Could you provide the faulty tools, please?

### To reproduce

1. Clone the repository
2. install de dependencies: `sudo dkp-pacman -S switch-dev switch-glfw switch-libwebp switch-curl switch-libmpv`
3. Run cmake:  `cmake -B build_switch -DPLATFORM_SWITCH=ON -DBUILTIN_NSP=ON`
4. See error:

```
CMake Error at scripts/forwarder/CMakeLists.txt:16 (message):
  Could not find hacbrewpack: try installing
  https://github.com/The-4n/hacBrewPack
```

### Screenshots

Non applicable

### Operating system

Non applicable

### Jellyfin Server

Non applicable

### Additional context

Trying to compile to test my translation to PT-BR that will be provide soon, after I can test it and see if do not "explode" any field in the application.

**Comment by hhgokraken** [comment]
And, in time.. really nice work!

**Comment by dragonflylee** [comment]
all needed extra package can be found in https://github.com/dragonflylee/switchfin/releases/tag/switch-portlibs

> [hacBrewPack-3.05-1-any.pkg.tar.zst](https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs/hacBrewPack-3.05-1-any.pkg.tar.zst) only worked on Linux x86-64

**Comment by hhgokraken** [comment]
Nice, I was able to compile after install all dependencies inside this links, but "failed" in the end.

Well, improvement.

```
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/14.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/portlibs/switch/lib/libEGL.a(glsl_types.cpp.o):(.data.rel.ro.local._ZN9glsl_type14f16mat2x3_typeE+0x0): multiple definition of `glsl_type::f16mat2x3_type'; /opt/devkitpro/portlibs/switch/lib/libuam.a(mesa-imported_compiler_glsl_types.cpp.o):(.data.rel.ro._ZN9glsl_type14f16mat2x3_typeE+0x0): first defined here
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/14.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/portlibs/switch/lib/libEGL.a(glsl_types.cpp.o):(.bss._ZN9glsl_type15_f16mat2x3_typeE+0x0): multiple definition of `glsl_type::_f16mat2x3_type'; /opt/devkitpro/portlibs/switch/lib/libuam.a(mesa-imported_compiler_glsl_types.cpp.o):(.bss._ZN9glsl_type15_f16mat2x3_typeE+0x0): first defined here
```

I will track a bit to see if I forgot something. I can build other homebrews with my current setup. I installed all files you pinpoint. Will install pacman inside a clean environment and try again.

```
/opt/devkitpro/devkitA64/bin/../lib/gcc/aarch64-none-elf/14.1.0/../../../../aarch64-none-elf/bin/ld: /opt/devkitpro/portlibs/switch/lib/libEGL.a(ir_hierarchical_visitor.cpp.o): in function `visit_tree(ir_instruction*, void (*)(ir_instruction*, void*), void*, void (*)(ir_instruction*, void*), void*)':
ir_hierarchical_visitor.cpp:(.text._Z10visit_treeP14ir_instructionPFvS0_PvES1_S3_S1_+0x0): multiple definition of `visit_tree(ir_instruction*, void (*)(ir_instruction*, void*), void*, void (*)(ir_instruction*, void*), void*)'; /opt/devkitpro/portlibs/switch/lib/libuam.a(mesa-imported_glsl_ir_hierarchical_visitor.cpp.o):ir_hierarchical_visitor.cpp:(.text._Z10visit_treeP14ir_instructionPFvS0_PvES1_S3_S1_+0x0): first defined here
```

I checked the lib:

```
# dkp-packman -Sl | grep uam
dkp-linux uam 1.1.0-1 [installed]
```

**Comment by hhgokraken** [comment]
I will provide the `i18n/pt-BR` as a PR to you, so you can compile, when you think it was appropriate. In the meantime I will try to solve here. Thanks!

**Comment by dragonflylee** [comment]
> I will provide the `i18n/pt-BR` as a PR to you, so you can compile, when you think it was appropriate. In the meantime I will try to solve here. Thanks!

you can enable github action for build

**Comment by dragonflylee** [comment]
@hhgokraken `switch-libmpv` and `switch-libmpv-deko3d` must not be installed at the same time,
first, you must remove deko3d version of libmpv by

```shell
sudo dkp-pacman -R switch-libmpv-deko3d
```
if you want build the opengl version, install follow pkg 

* https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs/hacBrewPack-3.05-1-x86_64.pkg.tar.zst
* https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs/switch-ffmpeg-7.1-1-any.pkg.tar.zst
* https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs/switch-libmpv-0.36.0-5-any.pkg.tar.zst
* https://github.com/dragonflylee/switchfin/releases/download/switch-portlibs/switch-nspmini-main-1-any.pkg.tar.zst

then build command below

```shell
sudo dkp-pacman -S switch-dev switch-glfw switch-libwebp switch-curl
cmake -B build_switch -DPLATFORM_SWITCH=ON -DBUILTIN_NSP=ON
cmake -C build_switch Switchfin.nro -j$(nproc)
```

**Comment by hhgokraken** [comment]
I will try that. Thank you.
