### ISSUE TITLE
Screen/backlight off

### ISSUE THREAD

**Issue by kevsestre** [dragonflylee/switchfin#60]
### Is your feature request related to a problem? Please describe.

When playing music, it's probably good if we can turn off the display. As a reference, sysdvr had the feature implemented here https://github.com/exelix11/SysDVR/commit/f1052e38c12f07d84b1a4a6b47e0e0307c363a5f

**Comment by dragonflylee** [comment]
@kevsestre As switchfin is not overlay sysmodule , so background music play is not possibe

another method is Implement another overlay sysmodule like https://github.com/tallbl0nde/TriPlayer
