### ISSUE TITLE
Windows 版的功能建议

### ISSUE THREAD

**Issue by kofzhanganguo** [dragonflylee/switchfin#61]
### Is your feature request related to a problem? Please describe.

1.希望可以显示影片详情的信息，而不是点击文件后就直接播放，因为影片详情有很多信息要素，比如演员，影片类型，视频文件，字幕等，还有就是可以显示类型，筛选等选项，便于查找视频文件，搜索的时候，也可以搜索具体NFO元数据里面的参数信息。

2.还有就是字幕问题，本身视频带外挂字幕，但是播放的时候，不会自动加载字幕，只能在播放的时候，手动去右上角点击那个设置齿轮图标，然后手动选择要加载的字幕。

3.Windows版的软件，好像没有键盘的快捷键设置，比如快进快退，音量的增加减少等，必须全程用鼠标操作这些设置，比如快进等需要鼠标拖动进度条，音量也是如此，还有就是右键是直接退出当前播放，好像右键是全局的返回键，点击鼠标右键后，能直接显示退出应用程序。
4.
![image](https://github.com/dragonflylee/switchfin/assets/32073931/688e00f9-1178-46e7-8ba3-25ed9e2f5635)
播放歌曲的时候，没有音量控制，无法控制音量的大小。
5.
![image](https://github.com/dragonflylee/switchfin/assets/32073931/87e8385e-ed58-4132-9f43-965048397aa8)
当播放歌曲时，点击右键返回后，音乐是在后台播放，而界面是不会显示当前播放的歌曲，这样就造成了不知道是啥东西在播放，想关闭歌曲，必须是随便播放点什么东西，比如视频或者是歌曲等，然后在关闭这个播放的内容，才能不让歌曲在后台播放了。

6.右侧的下拉条，想向下拉，如果不用滚轮操作的话，需要向上拉动滑块才可以，这个操作类似于手机操作，但是Windows是应该是向下拉才对。

7.使用最新的每日构建版本，是说支持EMBY的连接，但是我始终连接不上，端口不是默认的8096，是9090。
![image](https://github.com/dragonflylee/switchfin/assets/32073931/748465e0-92ca-4c8b-b4e9-6b2677df792a)
![image](https://github.com/dragonflylee/switchfin/assets/32073931/12f4b7f3-8d0f-41a2-8938-264dc7fb2289)
报这个错误。
EMBY是最新测试版
![image](https://github.com/dragonflylee/switchfin/assets/32073931/5f766014-a6d8-41f5-ad40-0ab4746842a3)

如果这些要求会造成软件卡顿，或者是速度变慢等，可以不需要，但是键盘快键键的操作应该要有，不然鼠标控制有的时候会很繁琐，比如快进，音量控制等。

目前播放使用上没多大问题，就是这些小细节而已，希望软件越来越完善，越来越好用。

**Comment by dragonflylee** [comment]
关于 Windows 播放界面下的快捷键

空格: 播放暂停
ESC: 退出播放
L/R: 前后快进
X: 显示/隐藏播放设置
Y: 显示/隐藏播放控制
P: 视频质量选择
F1: 显示视频信息

**Comment by dragonflylee** [comment]
@kofzhanganguo 关于 Emby 支持只有 emby 分支的 build 才是完全兼容的，主分支的理论上可以登录，返回401应该是用户名或者密码输错了
