### ISSUE TITLE
Need help to ship a config file with my cfw pack

### ISSUE THREAD

**Issue by laleeroy** [dragonflylee/switchfin#62]
I want to ship a config file with the predefined settings and url.
I logout the current user that I used to set the settings then
I tried to remove the user_id and it just black screen when launching the app
Same as with device (I believe this is device id?)

I don't know if it's really ok to ship a config file with device, id, and user id, I haven't tested it, Im not sure it Jellyfin will report it as one device for many user

**Comment by dragonflylee** [comment]
device id was generate by account inside HOS, and user id was get from jellyfin
example config template

```json
{
  "server_url": "http://192.168.1.5:8096",
  "servers": [
    {
      "id": "<YOUR ID>",
      "name": "nas",
      "os": "Linux",
      "urls": [
        "http://192.168.1.5:8096"
      ],
      "version": "10.8.13"
    }
  ],
  "setting": {
    "app_lang": "zh-Hans"
  }
}
```

**Comment by laleeroy** [comment]
> device id was generate by account inside HOS, and user id was get from jellyfin example config template
> 
> ```json
> {
>   "server_url": "http://192.168.1.5:8096",
>   "servers": [
>     {
>       "id": "<YOUR ID>",
>       "name": "nas",
>       "os": "Linux",
>       "urls": [
>         "http://192.168.1.5:8096"
>       ],
>       "version": "10.8.13"
>     }
>   ],
>   "setting": {
>     "app_lang": "zh-Hans"
>   }
> }
> ```

Thanks! Will try this later. 
Also, can I remove the id under server? Is it a unique id for each users from the jellyfin server?

**Comment by laleeroy** [comment]
> device id was generate by account inside HOS, and user id was get from jellyfin example config template
> 
> ```json
> {
>   "server_url": "http://192.168.1.5:8096",
>   "servers": [
>     {
>       "id": "<YOUR ID>",
>       "name": "nas",
>       "os": "Linux",
>       "urls": [
>         "http://192.168.1.5:8096"
>       ],
>       "version": "10.8.13"
>     }
>   ],
>   "setting": {
>     "app_lang": "zh-Hans"
>   }
> }
> ```

Im still getting a black screen
Here is my sample config file

{
  "server_url": "http://192.168.1.5:8096",
  "servers": [
    {
      "id": "<YOUR ID>",
      "name": "nas",
      "os": "Linux",
      "urls": [
        "http://192.168.1.5:8096"
      ],
      "version": "10.8.13"
    }
  ],
  "setting": {
    "app_lang": "zh-Hans"
    "force_directplay": true,                               
    "http_proxy_status": false,                             
    "player_bottom_bar": false
  }
}

**Comment by dragonflylee** [comment]
try latest nightly build please

**Comment by laleeroy** [comment]
> try latest nightly build please

It works, thank you!
One more thing before I closed the issue, I am using the deko3d version for switch, which one do you recommend to use? The neko3d or opengl?

**Comment by dragonflylee** [comment]
opengl version didn't support hwdec for now
so deko3d version is recommend
