### ISSUE TITLE
0.5.1版本无排序选项

### ISSUE THREAD

**Issue by kofzhanganguo** [dragonflylee/switchfin#64]
### Describe the bug

![image](https://github.com/user-attachments/assets/4d4bc94b-f3d9-411c-993d-624b39bea244)
![image](https://github.com/user-attachments/assets/8c84c7fc-00b4-4eb4-8759-8b69a9e75a84)
这个是0.5.1的版本截图。
![image](https://github.com/user-attachments/assets/967c06ef-52ca-4be5-ace7-f6e440dd9ec1)
![image](https://github.com/user-attachments/assets/cd83d4ce-44ad-4315-a682-3e1cf32386ce)
0.5.0没任何问题。
![image](https://github.com/user-attachments/assets/4210ea4f-da53-41a8-a79b-ecc3f384615d)
不知道是我的问题，还是软件问题。

### To reproduce

2. Tap on '....'

**Comment by kofzhanganguo** [comment]
还有一点，就是如何去掉更新的提示，因为我0.5.1有这个排序的问题，我只能用0.5.0，不想总是让软件提示更新提示，如何去掉每次打开软件，都显示更新提示。

**Comment by dragonflylee** [comment]
建议移动一下焦点，看看有没有排序选项

**Comment by kofzhanganguo** [comment]
> 建议移动一下焦点，看看有没有排序选项

没有任何焦点，和我截图的一样。

**Comment by kofzhanganguo** [comment]
![image](https://github.com/user-attachments/assets/e9edb5f8-2a4f-40c6-91f5-f50343e88fbd)
问题找到了，是这个选项的问题，把保存排序设置关闭就可以了。

**Comment by dragonflylee** [comment]
@kofzhanganguo  最新编译的 [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)  已经修复该问题

**Comment by kofzhanganguo** [comment]
> @kofzhanganguo 最新编译的 [![nightly](https://camo.githubusercontent.com/5ab7f1a946865ae5191baea212a789a5c542f67d85d8a34af0aaf42ca3bda318/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 已经修复该问题

我还是等正式版在更新吧。上次我说的几个建议，还是没有修复，比如播放歌曲后，右键返回后，还是在后台播放歌曲，而界面无任何显示播放的内容，所以就造成了不知道是啥东西在播放。
![image](https://github.com/user-attachments/assets/2015b2fc-bb75-4143-9257-41c7379ffd44)
这是在播放的歌曲，你点击返回，或者是右键，界面就不会显示播放的歌曲，这个有点难受啊。

**Comment by dragonflylee** [comment]
@kofzhanganguo  你在随便进入其他专辑就能看到播放内容了

**Comment by kofzhanganguo** [comment]
> @kofzhanganguo 你在随便进入其他专辑就能看到播放内容了

这个不能显示一下吗？非得在点击其他音乐才可以显示吗？

**Comment by dragonflylee** [comment]
@kofzhanganguo 您觉得显示在哪里比较合适呢？

**Comment by kofzhanganguo** [comment]
> @kofzhanganguo 您觉得显示在哪里比较合适呢？

![image](https://github.com/user-attachments/assets/339f2fff-608d-4d16-bf0d-5b738566781c)
比如这种吧，下面有个播放音乐的进度条提示，起码知道我在播放什么吧。

**Comment by dragonflylee** [comment]
如果只有专辑列表的界面有这个进度条 可以接受吗？（首页、其他视频列表没有）

**Comment by kofzhanganguo** [comment]
> 如果只有专辑列表的界面有这个进度条 可以接受吗？（首页、其他视频列表没有）

![image](https://github.com/user-attachments/assets/fc41e9f6-0d31-4026-b69f-fa342711998c)
其实有进度条了，我的意思就是返回后，歌曲播放时能给个小提示，知道我在播放什么，也就是首页上有个播放提示而已，其他都没事儿。

**Comment by dragonflylee** [comment]
最新版修复了排序选项
