### ISSUE TITLE
字幕无法自动加载，播放是必须手动选择字幕

### ISSUE THREAD

**Issue by kofzhanganguo** [dragonflylee/switchfin#65]
### Describe the bug

![image](https://github.com/user-attachments/assets/9babac1b-c86e-4daa-bb24-b3d7322bc7d4)
这是字幕文件
![image](https://github.com/user-attachments/assets/41e6df19-63d2-4b0e-bc6d-13f895034369)
然后字幕默认都是不显示，我不知道是我设置不对，还是怎么样，每次看带外挂字幕的视频，都是需要手动选择加载字幕。

### To reproduce

2. Tap on '....'

**Comment by dragonflylee** [comment]
最新编译的 [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)  已经修复该问题

**Comment by kofzhanganguo** [comment]
感谢作者的修复，还有能否添加个自动更新功能，比如自动下载更新，然后和关闭更新，不接收更新信息等的操作开关，不然有的时候打开总是提示更新，然后还没有选项关闭。

**Comment by kofzhanganguo** [comment]
> 最新编译的 [![nightly](https://camo.githubusercontent.com/8cf6f501ec9d5e03280249459dbcfeecc2e2c81186380bc615b41c2773717551/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 已经修复该问题

![image](https://github.com/user-attachments/assets/5c4d5672-3483-4e43-8f03-119e45e975fa)
![image](https://github.com/user-attachments/assets/8f5533c6-17d9-4a5b-a478-0a8971a5affb)
此最新编译版，仍然无法自动加载字幕，还是必须手动加载字幕，不知道是和原因。

**Comment by dragonflylee** [comment]
最新版修复了外挂字幕加载
