### ISSUE TITLE
解析弹幕 xml 时应通过整个标签名判断是不是弹幕

### ISSUE THREAD

**Issue by moetayuko** [dragonflylee/switchfin#66]
### Describe the bug

目前仅通过 xml 标签的首字母判断是不是弹幕
https://github.com/dragonflylee/switchfin/blob/e5f519523e9362b42e5ef045cd5fd34d66c02a60/app/src/activity/player_view.cpp#L336

xml 弹幕里还有 `datasize` 项，会被误判断成弹幕，然后产生一条类似 `[ERROR] DANMAKU: error decode: 484` 的报错。应将判断改为整个字符串匹配

**Comment by dragonflylee** [comment]
最新编译的 [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)  已经修复该问题
