### ISSUE TITLE
软件输入法框内无法复制粘贴

### ISSUE THREAD

**Issue by kofzhanganguo** [dragonflylee/switchfin#67]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/f743feba-08b2-4f9e-a6ce-2ef03b5c6af8)
![image](https://github.com/user-attachments/assets/dfd7b69b-0677-49e0-964b-549a9a343d25)
软件中所有的输入框内，都无法复制粘贴，这样操作起来很麻烦，必须手动打字，因文化有限，比如有日文等特殊字符，无法打出，就没办法进行搜索了。我只能打出来中文和英文，其他语言实在是打不出来。

**Comment by dragonflylee** [comment]
受 glfw 限制，短时间内暂时无法支持输入框的剪贴板，欢迎提交 PR 完善

**Comment by dragonflylee** [comment]
@kofzhanganguo 最新的  [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 用方向键选中搜索输入框，按 `X` 键即可粘贴

**Comment by dragonflylee** [comment]
@kofzhanganguo 得益于 @xfangfang 贡献的代码，最新的 [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 已支持在输入框中使用 `CTRL+V` 粘贴内容了

**Comment by kofzhanganguo** [comment]
> @kofzhanganguo 得益于 @xfangfang 贡献的代码，最新的 [![nightly](https://camo.githubusercontent.com/8cf6f501ec9d5e03280249459dbcfeecc2e2c81186380bc615b41c2773717551/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 已支持在输入框中使用 `CTRL+V` 粘贴内容了

嗯，感谢贡献，现在在Windows系统上可以实现Ctrl+V粘贴了。
