### ISSUE TITLE
可否作为本地播放器使用

### ISSUE THREAD

**Issue by AdventCirno** [dragonflylee/switchfin#68]
### Is your feature request related to a problem? Please describe.

即不连接到Jellyfin服务端直接当一个纯播放器使用，目前switch上并没有一款能支持webdav协议的播放器,NXMP已经很久没更新,而且到现在为止都不支持webdav。

### Describe the solution you'd like

当没有Jellyfin服务端的时候，单纯当个本地播放器，播放本地或者通过像webdav或其他协议挂载播放网络文件。

### Describe alternatives you've considered

鉴于Alist可以挂载各种网盘还可以用webdav共享，而且在PC和手机上都有服务端，如果能添加挂载Alist的功能就更好

**Comment by dragonflylee** [comment]
@AdventCirno 已经提供了对  Webdav 的支持，将如下内容添加到配置文件即可，用户可密码以及服务器地址请替换为您自己的

```json
{
  "remotes": [
    {
      "name": "xiaoya",
      "passwd": "guest_Api789",
      "url": "webdav://192.168.1.5:5678/dav",
      "user": "guest"
    }
  ]
}
```

**Comment by AdventCirno** [comment]
@dragonflylee 
尝试过添加config.json,但是打开软件还是在连接至jellyfin界面需要输入url。
![Screenshot_20240904_130648_com estrongs android pop](https://github.com/user-attachments/assets/d9f5fc2a-8cdd-4e84-af4e-b0002a37f3e7)
![Screenshot_20240904_122724_com huawei android launcher](https://github.com/user-attachments/assets/72631e51-7400-4321-963f-7bf39d71d65d)
![2024090412381400-5B7216B739EC78EC87BE86111C78E4A1](https://github.com/user-attachments/assets/84d0a31f-a60a-4204-a702-49c05e2dc87c)
我输入我本地dav路径(http://192.168.1.124:5244/dav)后会显示http status 401
![2024090412580200-5B7216B739EC78EC87BE86111C78E4A1](https://github.com/user-attachments/assets/af346027-e80c-4084-a988-28be5de9ae90)
输入webdav://192.168.1.124:5244/dav说不支持
输入http://192.168.1.124:5244/会json报错
![2024090412375700-5B7216B739EC78EC87BE86111C78E4A1](https://github.com/user-attachments/assets/8e6935f2-efd6-447a-b5e4-f9c149dba596)
我使用另一个ezremote软件能连上我的webdav地址，但是这东西只能传没办法看
![2024090412321200-5B7216B739EC78EC87BE86111C78E4A1](https://github.com/user-attachments/assets/cc5d3746-fa5f-49e4-a071-f83d08115a19)

**Comment by dragonflylee** [comment]
@AdventCirno 只要连接一次 Jellyfin (不用登陆) 就可以了，如果没有 Jellyfin 服务可以连接的话可以下配置如下内容

```json
{
  "remotes": [
    {
      "name": "Alist",
      "passwd": "123456",
      "url": "webdav://192.168.1.124:5244/dav",
      "user": "ns"
    }
  ],
  "server_url": "http://192.168.1.124:8096",
  "servers": [
    {
      "urls": [
        "http://192.168.1.124:8096"
      ]
    }
  ]
}
```

**Comment by AdventCirno** [comment]
> @dragonflylee 哦非常感谢，可以使用，swtich终于沦为机顶盒了，就是外挂字幕的话只能识别同一路径下相同文件名的字幕吗？

**Comment by dragonflylee** [comment]
外挂字幕目前还未做加载支持，mkv内嵌字幕是可以在正常播放的

后续版本可能会增加外挂字幕的支持

**Comment by dragonflylee** [comment]
@AdventCirno 最新的 [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 已支持加载外挂字幕了
