### ISSUE TITLE
IPTV Question?

### ISSUE THREAD

**Issue by laleeroy** [dragonflylee/switchfin#69]
Is there a workaround for Nintendo Switch to decode iptv media, I'm using m3u that I found on google

**Comment by dragonflylee** [comment]
first add config to '/switch/Switchfin/config.json' below

```json
{
  "remotes": [
    {
      "name": "local",
      "url": "file:///switch"
    }
  ]
}
```

then put `m3u` file to your SD Card `/switch`, 
after that start app you can see cloud icon in sidebar. and open the `m3u` in file broser which in right

**Comment by laleeroy** [comment]
> first add config to '/switch/Switchfin/config.json' below
> 
> ```json
> {
>   "remotes": [
>     {
>       "name": "local",
>       "url": "file:///switch"
>     }
>   ]
> }
> ```
> 
> then put `m3u` file to your SD Card `/switch`, after that start app you can see cloud icon in sidebar. and open the `m3u` in file broser which in right

Thank you! But the m3u files update gradually, can we put like a directory losting in the url instead of a localfile? I tried to paste a link but it lods forever

**Comment by dragonflylee** [comment]
@laleeroy another way is using jellyfin live tv, please refer https://github.com/dragonflylee/switchfin/issues/27

https://jellyfin.org/docs/general/server/live-tv/setup-guide/

**Comment by laleeroy** [comment]
> @laleeroy another way is using jellyfin live tv, please refer #27
> 
> https://jellyfin.org/docs/general/server/live-tv/setup-guide/

Yes Im using it aswell, unfortunately it requires transcoding from the server for the switch to be able to play the media 😞

**Comment by dragonflylee** [comment]
@laleeroy transcoding is no need in jellyfin live tv  by [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) now, force diect streaming

**Comment by laleeroy** [comment]
> @laleeroy transcoding is no need in jellyfin live tv by [![nightly](https://camo.githubusercontent.com/8cf6f501ec9d5e03280249459dbcfeecc2e2c81186380bc615b41c2773717551/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) now, force diect streaming

Thanks, it is working!
I also noticed that when using old npdm tool from switch-tools, when you compile the forwarder in hacbrew with latest flags required for newer version of atmosphere, the forwarder becomes backwards compatible.
Maybe you can use old npdmtool so the forwarder of switchfin becomes backwards compatible to latest and lower version of atmosphere?

Sorry for my bad English
