### ISSUE TITLE
支持 emoji 弹幕

### ISSUE THREAD

**Issue by moetayuko** [dragonflylee/switchfin#71]
### Is your feature request related to a problem? Please describe.

目前弹幕中的 emoji 会渲染成中间有一把叉的方块，希望增加 emoji 支持

### Additional context

我试着在 borealis 里加载 emoji 字体并设为 Application::getDefaultFont() 的 fallback 但并没有效果，可能姿势不对

**Comment by dragonflylee** [comment]
修复于 https://github.com/dragonflylee/switchfin/commit/5a51b888f97210d018e510fe2e4f3ae409f2985a

可以下载最新的  [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)  试用

**Comment by moetayuko** [comment]
> 修复于 [5a51b88](https://github.com/dragonflylee/switchfin/commit/5a51b888f97210d018e510fe2e4f3ae409f2985a)
> 
> 可以下载最新的 [![nightly](https://camo.githubusercontent.com/8cf6f501ec9d5e03280249459dbcfeecc2e2c81186380bc615b41c2773717551/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6e696768746c792d6275696c642d677265656e)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev) 试用

这个 commit 里带的字体确实能用，但是看着很丑：
![图片](https://github.com/user-attachments/assets/3a5f307a-f89e-4235-a9e9-2cbc670ba0e5)
![图片](https://github.com/user-attachments/assets/72e7c4d5-47a8-4d3c-95c9-0878fcc3e2cf)


我之前测试不工作的是这个彩色字体 https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji_WindowsCompatible.ttf ，现在用他替换掉 https://github.com/dragonflylee/switchfin/commit/5a51b888f97210d018e510fe2e4f3ae409f2985a 的字体再编译出来仍然会渲染成带一把叉的方块。字体似乎是通过 nanovg 这个库渲染的，是他不支持彩色 emoji 吗

**Comment by dragonflylee** [comment]
@miraficus 参考 https://github.com/xfangfang/wiliwili/issues/281#issuecomment-1936898693

**Comment by moetayuko** [comment]
> @miraficus 参考 [xfangfang/wiliwili#281 (comment)](https://github.com/xfangfang/wiliwili/issues/281#issuecomment-1936898693)

> 需要注意的是目前emoji应该是不支持那种带颜色的。

有总比没有强。。
