### ISSUE TITLE
subtitles enabled by default 

### ISSUE THREAD

**Issue by RemagOfficial** [dragonflylee/switchfin#72]
### Describe the bug

when watching media with subtitles they are set to enabled until disabled with no setting to disable this

### To reproduce

1. Start watching any media with subtitles
2. See error

### Operating system

18.1.0|AMS 1.7.1|S

### Jellyfin Server

10.9.10 Windows

**Comment by AaryanMadal** [comment]
try this
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by AmjedKhaled165** [comment]
download

https://bit.ly/4eugCty
I put the necessary dlls in the archive

**Comment by RemagOfficial** [comment]
reported those bots

**Comment by dragonflylee** [comment]
@RemagOfficial  add new option `Autoload subtitles` https://github.com/dragonflylee/switchfin/commit/04f6066b6a466f52b1a31b2f627e185ecc49ad0d

you can test by [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)
