### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by tlover-code** [dragonflylee/switchfin#77]
### Is your feature request related to a problem? Please describe.

I have translated it into Vietnamese; can you help me add it to your wonderful application? 
In i18n, Vietnamese is abbreviated as vi_VN or vi.
[hints.json](https://github.com/user-attachments/files/17550497/hints.json)
[main.json](https://github.com/user-attachments/files/17550498/main.json)

**Comment by dragonflylee** [comment]
thanks for provide translation, you can test with [![nightly](https://img.shields.io/badge/nightly-build-green)](https://nightly.link/dragonflylee/switchfin/workflows/build.yaml/dev)

**Comment by tlover-code** [comment]
[main_fix_wrong_text.json](https://github.com/user-attachments/files/17553979/main_fix_wrong_text.json)
There was a typo, so I corrected it. I hope it will appear in the official version soon.
