### ISSUE TITLE
Timeout / character limit

### ISSUE THREAD

**Issue by 10kmotorola** [dragonflylee/switchfin#9]
When trying to connect to the http server, I'm just presented with a timeout. And when trying to connect through my https reverse proxy, the url is past the character limit. Is the character limit like, a restriction of the Switch?

**Comment by dragonflylee** [comment]
@mariospicross as default port for jellyfin is 8096，maybe port was missing in the url input box, such as 
http://[your ip]:8096

another way to download dev build from https://github.com/dragonflylee/switchfin/actions/runs/5886926339
which fixed  character limit

**Comment by 10kmotorola** [comment]
well, restarted my Switch, used the latest dev build, used my https connection, and everything's working now. thanks!
